### ISSUE TITLE
"issueベース開発"のレビュー依頼（MVPまで）

### ISSUE THREAD

**Issue by Ryocchi-Muscle** [Ryocchi-Muscle/fitapp-api#6]
Projectsで計画と工数を配置しましたので、ご確認お願い致します。

現状MVPリリースまでの計算です。

**Comment by shota-hope** [comment]
ご提出ありがとうございます。
気になった点をコメントさせていただきます。

> ユーザー情報登録 (名前)　削除
ストーリーポイント3

- 例えば上記について、恐らくユーザー情報の編集削除はフォームで作られると思うので、削除というのは不要に思いました。（空欄で登録→削除するということを想定しました）
- また、issueの分割はとても大事だと思いますがユーザーの編集、削除について一つの属性ごとにissueにするのは個人的には少し細かすぎるようにも感じましたがいかがでしょうか？

ご確認よろしくお願いいたします。

**Comment by Ryocchi-Muscle** [comment]
おおの講師レビューありがとうござます。

> 例えば上記について、恐らくユーザー情報の編集削除はフォームで作られると思うので、削除というのは不要に思いました。（空欄で登録→削除するということを想定しました）

仰る通りこちら不要でしたので、削除しました。

> issueの分割はとても大事だと思いますがユーザーの編集、削除について一つの属性ごとにissueにするのは個人的には少し細かすぎるようにも感じましたがいかがでしょうか？

こちらも仰る通り、ユーザー情報の編集はあっても削除機能は存在しないため、ユーザー情報系の削除工程は全て削除いたしました。

上記修正いたしましたので、再度ご確認お願い致します。
他にも不要な点等ございましたら、ご指摘頂きたく思います。

＜ご相談＞
機能に関して
MVPにしては、基本ユーザー機能とトレーニング記録のみのため、物足りないかなと感じましたが、計画的にはProjectsで予定しているissue数で問題ございませんでしょうか。
第２段階の実装も一緒にissueを作成したほうがよろしいでしょうか。

**Comment by kenchasonakai** [comment]
LGTMです

> 機能に関して
MVPにしては、基本ユーザー機能とトレーニング記録のみのため、物足りないかなと感じましたが、計画的にはProjectsで予定しているissue数で問題ございませんでしょうか。
第２段階の実装も一緒にissueを作成したほうがよろしいでしょうか。

MVPなので問題ないと思います

**Comment by Ryocchi-Muscle** [comment]
中井講師ありがとうございます。
MVPはこれで進めていきます。
